### ISSUE TITLE
Setting UpperValue > MaximumValue in code/xaml should throw an Exception

### ISSUE THREAD

**Issue by MarcusSpecht** [halkar/xamarin-range-slider#141]
I am using Range-Slider on Droid, iOS and UWP with Xamarin.Forms 3.0. I accidentally set uppervalue=100 and maximumvalue=30. On All Platforms  the view loaded but only UWP showed both thumbs. On iOS and Android I only saw the left thumb since the right thumb wasn't drawn at all or outside of the viewport. It took me quite a long time to find my mistake especially since it seemed to work on UWP.

I think it would be best to throw an Exception like "UpperValue cannot be greater than MaximumValue".

**Comment by halkar** [comment]
Sorry, can't agree. Throwing an exception will cause a lot of random problems on component initialisation as there is no specific order in which component should be initialised.

**Comment by charlesroddie** [comment]
Sliders have a lot of problems with this since they often involve the mutating of different variables (min, max, value, etc.) separately (e.g. through bindings). Really they shouldn't do this as it enables invalid data; instead there should be a method to set all variables simultaneously, which should throw an error on invalid data. But separate variables allowing temporary invalid data is what we are stuck with. So @MarcusSpecht is right in theory but @halkar in practice.
